// Basic terms — the liability boundary for a tool that emits investment-adjacent output.
export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-sm leading-relaxed text-gray-300">
      <h1 className="mb-6 text-2xl font-bold text-gray-100">Terms of Use</h1>

      <h2 className="mb-2 mt-6 text-base font-semibold text-gray-100">1. Decision-support only — not investment advice</h2>
      <p>
        This tool produces AI-generated market research for preliminary screening. Nothing it
        outputs — including scores, rankings, grades, INVEST/WATCH/PASS language, or return
        ranges — is investment advice, a recommendation, or an offer to buy or sell securities.
        It is not produced by a licensed investment adviser. You are solely responsible for any
        decision you make.
      </p>

      <h2 className="mb-2 mt-6 text-base font-semibold text-gray-100">2. Accuracy</h2>
      <p>
        Reports are generated by large language models from public web sources. Figures may be
        incomplete, stale, or wrong despite the tool&apos;s sourcing and freshness safeguards.
        Verify every material figure against a primary source before acting on it. Return
        figures are scenario-derived multiples: gross unless explicitly labeled net, and net
        figures reflect only a coarse stage-banded dilution assumption — all before fees,
        taxes, and time-value.
      </p>

      <h2 className="mb-2 mt-6 text-base font-semibold text-gray-100">3. Data handling</h2>
      <p>
        Prompts and any uploaded materials are processed by third-party AI and search providers
        (Google, Anthropic, OpenAI, Tavily) to produce the analysis, and results are stored on
        this deployment&apos;s server. Do not upload confidential, NDA-covered, or material
        non-public information unless this deployment explicitly provides data-handling
        guarantees for it. Deployments in public-data mode disable uploads entirely.
      </p>

      <h2 className="mb-2 mt-6 text-base font-semibold text-gray-100">4. No warranty; limitation of liability</h2>
      <p>
        The service is provided &quot;as is&quot; without warranties of any kind. To the maximum
        extent permitted by law, the operator is not liable for any loss arising from use of, or
        reliance on, the service or its output.
      </p>

      <p className="mt-8 text-xs text-gray-500">
        <a href="/app" className="underline hover:text-gray-300">← Back to the app</a>
      </p>
    </main>
  );
}
